### ISSUE TITLE
rqt_plot failed due to kobuki_qtestsuite?

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki_desktop#10]
```
$ rosrun rqt_plot rqt_plot 
rqt_plot.plot: importing PyQtGraphDataPlot
rqt_plot.plot: import of PyQtGraphDataPlot failed
rqt_plot.plot: importing MatDataPlot
rqt_plot.plot: importing QwtDataPlot
WARNING: Package name "swig-wx" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
WARNING: Package name "swig-wx" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/rqt_plot/rqt_plot", line 10, in <module>
    sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plot.add_arguments))
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rqt_gui/main.py", line 57, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/main.py", line 468, in main
    plugins = plugin_manager.find_plugins_by_name(plugin)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 118, in find_plugins_by_name
    for plugin_id, plugin_full_name in self.get_plugins().items():
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 124, in get_plugins
    self.discover()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 108, in discover
    self._plugin_menu.add_plugin(plugin_descriptor)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_menu.py", line 79, in add_plugin
    self._enrich_action(action, action_attributes, base_path)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_menu.py", line 130, in _enrich_action
    raise UserWarning('icon "%s" not found' % str(path))
UserWarning: icon "../src/kobuki_qtestsuite/resources/images/kobuki_icon.png" not found
```

**Comment by 130s** [comment]
I confirmed that this happens when `kobuki*` are installed (although I haven't seen without them). [Discussion about its root cause has already started](http://groups.google.com/group/ros-sig-rqt/browse_thread/thread/56866547d12c4eff?hl=en).

**Comment by yhju** [comment]
@130s Thanks for your comment

**Comment by 130s** [comment]
If you're usingpublic debian version, root cause of the issue (`qt_gui_core` metapackage) is now rollbacked so that this issue should not happen (the issue still persists if you use that metapackage from source though).

**Comment by yhju** [comment]
I'm using public debs for testing and verifying. It resolved now.
Thanks!!

**Comment by 130s** [comment]
Since I still see this issue with source install, I think it's worth re-opening (I don't have a privilede to re-open).

rqt 1a4c407fc118b95f3e9077f4838898b78bc4fa0c
qt_gui_core 4efcbd4b00865df02e159ceefbf8b87d9ed3fb4f
ros-groovy-kobuki 0.3.5-0quantal-20130326-1055-+0000

```
$ rqt
Traceback (most recent call last):
  File "~/ROS/groovy_quantal/catkin_ws/devel/bin/rqt", line 5, in <module>
    exec(fh.read())
  File "<string>", line 16, in <module>
  File "~/ROS/groovy_quantal/catkin_ws/src/rqt/rqt_gui/src/rqt_gui/main.py", line 57, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider)
  File "~/ROS/groovy_quantal/catkin_ws/src/qt_gui_core/qt_gui/src/qt_gui/main.py", line 478, in main
    plugin_manager.discover()
  File "~/ROS/groovy_quantal/catkin_ws/src/qt_gui_core/qt_gui/src/qt_gui/plugin_manager.py", line 108, in discover
    self._plugin_menu.add_plugin(plugin_descriptor)
  File "~/ROS/groovy_quantal/catkin_ws/src/qt_gui_core/qt_gui/src/qt_gui/plugin_menu.py", line 79, in add_plugin
    self._enrich_action(action, action_attributes, base_path)
  File "~/ROS/groovy_quantal/catkin_ws/src/qt_gui_core/qt_gui/src/qt_gui/plugin_menu.py", line 130, in _enrich_action
    raise UserWarning('icon "%s" not found' % str(path))
UserWarning: icon "../src/kobuki_qtestsuite/resources/images/kobuki_icon.png" not found
```

**Comment by stonier** [comment]
Let's keep an eye on https://github.com/ros-visualization/qt_gui_core/issues/16. 130s can you update us if it gets back to a working status?

For the moment, just rewinding qt_gui_core by 1 commit should work.

**Comment by stonier** [comment]
Working for me now.
